
language: node_js

env:
     - DB=postgresql://postgres@localhost:5432/reg_numbers
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database reg_numbers;' -U postgres
  - psql -U postgres -d reg_numbers -a -f table.sql 

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2